--Thomas Melles

--DROP TABLES

DROP TABLE JUDGESHIPS;
DROP TABLE NOMINATION;
DROP TABLE NOMINEE;

--CREATE TABLES

CREATE TABLE NOMINEE (
    PersonID CHAR (5) NOT NULL,
    NomineeFirst VARCHAR (15) NOT NULL,
    NomineeMiddle VARCHAR (10),
    NomineeLast VARCHAR (20) NOT NULL,
    Birthdate DATE NOT NULL,
    LawSchool VARCHAR (50) NOT NULL,
    CONSTRAINT NOMINEE_PK PRIMARY KEY (PersonID)
);

CREATE TABLE NOMINATION (
    NominationID CHAR (6) NOT NULL,
    PersonID CHAR (5) NOT NULL,
    NominationDate DATE NOT NULL,
    NomniationType VARCHAR (15) NOT NULL,
    President VARCHAR (15) NOT NULL,
    Percentage NUMBER (*,1),
    Outcome VARCHAR (15),
    CONSTRAINT NOMINATION_PK PRIMARY KEY (NominationID),
    CONSTRAINT NOMINATIONFOREIGN_PK FOREIGN KEY (PersonID) REFERENCES NOMINEE (PersonID)
  

);

CREATE TABLE JUDGESHIPS (
    PersonID CHAR (5) NOT NULL,
    Judgeships VARCHAR (50) NOT NULL,
    CONSTRAINT JUDGE_PK PRIMARY KEY (PersonID, Judgeships),
    CONSTRAINT JUDGEFOREIGN_PK FOREIGN KEY (PersonID) REFERENCES NOMINEE (PersonID)
);
